spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/mobile_ms
      username: postgres
      password: root
      
  jpa:
    generate-ddl: true
    show-sql: true
    
mobilestore:
  vendor-name: AMAZON
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/  
